<html>
<head>
    <title>webfabric.com : $title$</title>
    <link type="text/css" rel="stylesheet" href="$base$/style/core.css"/>
    <script type="text/javascript" src="$base$/js/jquery-1.3.2.min.js"></script>
    <script type="text/javascript" src="$base$/js/core.js"></script>
    <script type="text/javascript" src="$base$/js/behaviour.js"></script>
    <script type="text/javascript" src="$base$/js/ahah.js"></script>
    <script type="text/javascript" src="$base$/js/bindings.js"></script>
    $head$
</head>
<body>
<div class="header">
    <ul class="menu">
        <li class="item"><a href="$base$/">webfabric</a></li>
        <li class="item"><a href="$base$/test/">tests</a></li>
        <li class="item"><a href="http://webfabric.googlecode.com/">code</a></li>
        <li class="item"><a href="http://server.bodar.com/teamcity/">build</a></li>
    </ul>
</div>
<div class="content">
    <h1>webfabric.com : $title$</h1>

    $body$
</div>
<div class="footer">
    copyleft webfabric.com
</div>
</body>
</html>