<html>
<head>
    <title>webfabric.org : $title$</title>
    <link type="text/css" rel="stylesheet" href="$base$/style/core.css"/>
    <script type="text/javascript" src="$base$/js/jquery-1.3.2.min.js"></script>
    <script type="text/javascript" src="$base$/js/core.js"></script>
    <script type="text/javascript" src="$base$/js/behaviour.js"></script>
    <script type="text/javascript" src="$base$/js/ahah.js"></script>
    <script type="text/javascript" src="$base$/js/bindings.js"></script>
    $head$
</head>
<body>