<html>
<head>
    <title>Properties</title>
    <style type="text/css">
        textarea#properties {
            width: 100%;
        }
    </style>
</head>
<body>
    <form action="?" method="POST">
        <!--<label for="Search">Search</label><input id="Search" type="text"/>-->
        <textarea id="properties" name="properties" rows="20" cols="20">$properties$</textarea>
        <input type="submit" value="Save"/>
    </form>
</body>
</html>

